### ISSUE TITLE
Tracking Scenario Completion

### ISSUE THREAD

**Issue by sraboy** [sraboy/7kaa#1]
- [x] UI checkboxes: https://github.com/sraboy/7kaa/tree/vs_scenario_completion
- [x] Tracking scenario games: https://github.com/sraboy/7kaa/tree/vs_gamefile
- [x] Clear status/manually check/uncheck
- [x] Player stats: https://github.com/sraboy/7kaa/tree/vs_player_stats
- [x] merge them all
